### ISSUE TITLE
Different between this and TSDX external?

### ISSUE THREAD

**Issue by adi-works** [aminnairi/rollup-plugin-external#7]
See how TSDX does it:

* https://github.com/formium/tsdx/blob/462af2d002987f985695b98400e0344b8f2754b7/src/createRollupConfig.ts#L63
* https://github.com/formium/tsdx/blob/master/src/utils.ts#L23

**Comment by aminnairi** [comment]
Hi adi518 and thanks for your issue.

By default, TSDX doesn ot take into account several features that are inherited from the `package.json` such as the ability to exclude or include packages, to specify another path for your `package.json`, to exclude using external built-in Node modules, bundled dependencies, dependencies, optional dependencies & peer dependencies.

These are all `package.json` configuration that you can use, but TSDX only does a shallow job of include all dependencies (those that do not start with `.`).

When your configuration gets a little bit tricky, this package does the heavy lifting of include or excluding certain package, according to your needs and the `package.json` specifications.

I hope that I answered your question, let me know if something is not clear and do not hesitate to reopen this issue if needed!
